// src/constants/GameConstants.ts

export const GAME_CONSTANTS = {
  // Board settings
  BOARD_SIZE: 25,
  MAX_PLAYERS: 6,
  GAME_DURATION: 180, // seconds
  GAME_SPEED: 220, // ms between moves
  
  // Input handling
  MIN_DIRECTION_CHANGE_INTERVAL: 100, // ms
  MIN_SWIPE_DISTANCE: 30, // pixels
  
  // Power-ups
  POWERUP_SPAWN_ATTEMPTS: 200,
  MAX_POWERUPS: 5,
  POWERUP_MIN_INTERVAL: 20000, // ms
  POWERUP_MAX_INTERVAL: 30000, // ms
  
  // Performance
  TARGET_FPS: 60,
  SYNC_INTERVAL: 500, // ms for Firebase batching
  
  // AI
  AI_DIRECTION_CHANGE_COOLDOWN: 500, // ms
  AI_RISK_RADIUS: 3, // cells
  AI_PREDICTION_STEPS: 5
};

export const AI_CONSTANTS = {
  RISK_CALCULATION_RADIUS: 3,
  PATHFINDING_DEPTH: 5,
  DECISION_COOLDOWN: 100,
  PERSONALITY_VARIATION: 0.3
};

export const PERFORMANCE_CONSTANTS = {
  OPTIMIZATION_THRESHOLD: 45, // FPS threshold for optimizations
  MEMORY_WARNING_THRESHOLD: 50, // MB
  FRAME_TIME_HISTORY_SIZE: 60,
  GARBAGE_COLLECTION_INTERVAL: 30000 // ms
};

export const VISUAL_CONSTANTS = {
  PARTICLE_COUNT_HIGH: 100,
  PARTICLE_COUNT_MEDIUM: 50,
  PARTICLE_COUNT_LOW: 20,
  ANIMATION_DURATION_FAST: 200,
  ANIMATION_DURATION_NORMAL: 500,
  ANIMATION_DURATION_SLOW: 1000,
  WAVE_NOTIFICATION_DURATION: 3000,
  EXPLOSION_PARTICLE_BASE: 8,
  FOOD_SEARCH_RADIUS: 10,
  SAFE_DISTANCE_THRESHOLD: 3
};

export const UI_CONSTANTS = {
  MOBILE_BREAKPOINT: 768,
  TOUCH_SENSITIVITY: 30,
  NOTIFICATION_FADE_TIME: 300,
  HUD_UPDATE_INTERVAL: 100
};